### ISSUE TITLE
Error Handling: Master Issue

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#174]
Following updates to the error handling is required:

- [x] Handling Typed BDK Errors
- [x] Dedicated BBError Type, that has fields like: 
`title, message, solution, stacktrace`
- [x] General errors should be a snack box that doesnt take up screen real estate
- [x] Form specific errors can show underneath the input field where validation fails
- [x] Clearing cubit error states properly

**Comment by i5hi** [comment]
- [ ] Add catch for PanicException to catch errors in electrum server and attempt to resync client
 
 Note panicexception is a general rust error, so it could be unrelated to electrum - but since we are noticing electrum causing panics, let us debug and check inputs going into the electrum related calls.

**Comment by i5hi** [comment]
Closing this since most of the core stuff is done. Opening a new issue just for the Panic Exception.
